Repository opnsense/core, pull requests merged in 2025-03, with the labels that each got.

#8392 interface/vip: Adjust help text for nosync option
  src/opnsense/mvc/app/controllers/OPNsense/Interfaces/forms/dialogVip.xml
Labels: cleanup

#8378 wizard: reimplement system setup
  plist
  src/Makefile
  src/etc/config.xml.sample
  src/etc/inc/console.inc
  src/etc/inc/filter.lib.inc
  src/etc/inc/interfaces.inc
  src/etc/inc/system.inc
  src/etc/inc/xmlparse.inc
  src/opnsense/mvc/app/controllers/OPNsense/Core/Api/InitialSetupController.php
  src/opnsense/mvc/app/controllers/OPNsense/Core/InitialSetupController.php
  src/opnsense/mvc/app/controllers/OPNsense/Core/forms/wizard_general_info.xml
  src/opnsense/mvc/app/controllers/OPNsense/Core/forms/wizard_network_lan.xml
  src/opnsense/mvc/app/controllers/OPNsense/Core/forms/wizard_network_wan.xml
  src/opnsense/mvc/app/controllers/OPNsense/Core/forms/wizard_root_password.xml
  src/opnsense/mvc/app/models/OPNsense/Core/ACL/ACL.xml
  src/opnsense/mvc/app/models/OPNsense/Core/InitialSetup.php
  src/opnsense/mvc/app/models/OPNsense/Core/InitialSetup.xml
  src/opnsense/mvc/app/models/OPNsense/Core/Menu/Menu.xml
  src/opnsense/mvc/app/views/OPNsense/Core/initial_setup.volt
  src/opnsense/scripts/shell/setaddr.php
  src/opnsense/scripts/system/get_timezones.php
  src/opnsense/service/conf/actions.d/actions_system.conf
  src/wizard/system.xml
  src/www/index.php
  src/www/interfaces.php
  src/www/javascript/wizard/autosuggest.js
  src/www/javascript/wizard/disablekeys.js
  src/www/javascript/wizard/suggestions.js
  src/www/services_opendns.php
  src/www/system_general.php
  src/www/wizard.php
Labels: feature

#8396 OpenVPN: Add support for various options
  src/opnsense/mvc/app/controllers/OPNsense/OpenVPN/forms/dialogInstance.xml
  src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.php
  src/opnsense/mvc/app/models/OPNsense/OpenVPN/OpenVPN.xml
Labels: feature

#8405 dnsmasq: When dhcp-fqdn is set, there must be a domain without an address set as default
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/Api/SettingsController.php
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/general.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: bug

#8408 dnsmasq: Use interface directly as tag in dhcp options
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPoption.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8411 dnsmasq: Allow domain overrides to be optionally sorted by sequence number to support strict-order
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDomainOverride.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8413 dnsmasq: Add missing hint for lease time default value
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
Labels: cleanup

#8447 dnsmasq: Add add-mac, add-subnet and strip-subnet options
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/general.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8448 dnsmasq: Add option6 to support DHCPv6 options
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPoption.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8453 interfaces/vip: Fix advanced mode visibility
  src/opnsense/mvc/app/views/OPNsense/Interface/vip.volt
Labels: cleanup

#8461 dnsmasq: Change dhcptags position in menu to align with c9b1af5
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Menu/Menu.xml
Labels: cleanup

#8456 dnsmasq: Add DHCPv6 options
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPmatch.xml
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPoption.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/scripts/dns/dnsmasq_dhcp_options.py
  src/opnsense/service/conf/actions.d/actions_dnsmasq.conf
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8449 dnsmasq: Add router advertisement options
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/general.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8464 dnsmasq: Adjust filter on interface field so group interfaces are filtered
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
Labels: cleanup

#8468 dnsmasq: Add internalModelUseSafeDelete to prevent deletion of currently used tags
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/Api/SettingsController.php
Labels: cleanup

#8482 dnsmasq: Require interface when ra_mode is selected due to ra-param interface requirement.
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
  src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: cleanup

#8483 auth/user: Remove styles conflicting with 387c381
  src/opnsense/mvc/app/views/OPNsense/Auth/user.volt
Labels: cleanup

#8465 dnsmasq: Add filter function for interfaces and tags with multiselect
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/Api/SettingsController.php
  src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt
  src/opnsense/www/js/opnsense_ui.js
Labels: feature

#8493 firewall/filter: Use fetch_options from opnsense_ui.js to build interface_select selectpicker
  src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/FilterController.php
  src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt
  src/opnsense/www/js/opnsense_ui.js
Labels: cleanup

#8497 dnsmasq: Add full dhcp-host support for IPv4 and IPv6
  src/etc/inc/plugins.inc.d/dnsmasq.inc
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogHostOverride.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8500 dnsmasq: Change add_mac OptionValue from default to standard to satisfy lint
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: cleanup

#8509 auth/user: Fix url hash in link so redirection shows the correct menu path
  src/opnsense/mvc/app/views/OPNsense/Auth/user.volt
Labels: cleanup
