Repository opnsense/core, pull requests merged in 2025-06, with the labels that each got.

#8813 dnsmasq: dhcp-host are allowed to have duplicate partial IPv6 addresses
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
Labels: cleanup

#8814 dnsmasq: Implement domain_type to select between adding domain to range or interface
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8822 dnsmasq: Change domain_type default to range to retain current default logic
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
Labels: cleanup

#8781 automation/filter: Assorted UI updates
  src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/FilterController.php
  src/opnsense/mvc/app/controllers/OPNsense/Firewall/forms/dialogFilterRule.xml
  src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt
  src/opnsense/www/js/opnsense_ui.js
Labels: feature

#8842 mvc: Replace camelCase API notation with snake_case
  src/opnsense/mvc/app/views/OPNsense/CaptivePortal/index.volt
  src/opnsense/mvc/app/views/OPNsense/CaptivePortal/vouchers.volt
  src/opnsense/mvc/app/views/OPNsense/Cron/index.volt
  src/opnsense/mvc/app/views/OPNsense/DHCPv4/leases.volt
  src/opnsense/mvc/app/views/OPNsense/DHCPv6/leases.volt
  src/opnsense/mvc/app/views/OPNsense/DHCRelay/relay.volt
  src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt
  src/opnsense/mvc/app/views/OPNsense/Diagnostics/routes.volt
  src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
  src/opnsense/mvc/app/views/OPNsense/Firewall/category.volt
  src/opnsense/mvc/app/views/OPNsense/Firewall/group.volt
  src/opnsense/mvc/app/views/OPNsense/IDS/index.volt
  src/opnsense/mvc/app/views/OPNsense/IDS/policy.volt
  src/opnsense/mvc/app/views/OPNsense/IPsec/key_pairs.volt
  src/opnsense/mvc/app/views/OPNsense/IPsec/pre_shared_keys.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/bridge.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/gif.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/gre.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/lagg.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/loopback.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/overview.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/vip.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/vlan.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/vxlan.volt
  src/opnsense/mvc/app/views/OPNsense/Monit/index.volt
  src/opnsense/mvc/app/views/OPNsense/Routing/configuration.volt
  src/opnsense/mvc/app/views/OPNsense/Syslog/index.volt
  src/opnsense/mvc/app/views/OPNsense/TrafficShaper/index.volt
  src/opnsense/mvc/app/views/OPNsense/Unbound/acl.volt
  src/opnsense/mvc/app/views/OPNsense/Unbound/overrides.volt
  src/opnsense/mvc/app/views/OPNsense/Unbound/overview.volt
  src/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt
Labels: cleanup

#8843 mvc: Replace camelCase API notation with snake_case, some more spots that were missed
  src/opnsense/mvc/app/views/OPNsense/CaptivePortal/index.volt
  src/opnsense/mvc/app/views/OPNsense/Cron/index.volt
  src/opnsense/mvc/app/views/OPNsense/DHCRelay/relay.volt
  src/opnsense/mvc/app/views/OPNsense/Diagnostics/arp.volt
  src/opnsense/mvc/app/views/OPNsense/Diagnostics/fw_log.volt
  src/opnsense/mvc/app/views/OPNsense/Diagnostics/netflow.volt
  src/opnsense/mvc/app/views/OPNsense/Diagnostics/networkinsight.volt
  src/opnsense/mvc/app/views/OPNsense/Diagnostics/systemactivity.volt
  src/opnsense/mvc/app/views/OPNsense/Firewall/alias.volt
  src/opnsense/mvc/app/views/OPNsense/Firewall/category.volt
  src/opnsense/mvc/app/views/OPNsense/Firewall/group.volt
  src/opnsense/mvc/app/views/OPNsense/IDS/index.volt
  src/opnsense/mvc/app/views/OPNsense/IDS/policy.volt
  src/opnsense/mvc/app/views/OPNsense/IPsec/key_pairs.volt
  src/opnsense/mvc/app/views/OPNsense/IPsec/tunnels.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/lagg.volt
  src/opnsense/mvc/app/views/OPNsense/Interface/overview.volt
  src/opnsense/mvc/app/views/OPNsense/Syslog/index.volt
  src/opnsense/mvc/app/views/OPNsense/TrafficShaper/index.volt
  src/opnsense/mvc/app/views/OPNsense/Unbound/acl.volt
  src/opnsense/mvc/app/views/OPNsense/Unbound/dot.volt
  src/opnsense/mvc/app/views/OPNsense/Unbound/general.volt
  src/opnsense/mvc/app/views/OPNsense/Unbound/overview.volt
  src/opnsense/mvc/app/views/OPNsense/Wireguard/general.volt
Labels: cleanup

#8846 CaptivePortal: Implement base_bootgrid_table and base_apply_button
  src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/Api/SettingsController.php
  src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/IndexController.php
  src/opnsense/mvc/app/controllers/OPNsense/CaptivePortal/forms/dialogZone.xml
  src/opnsense/mvc/app/views/OPNsense/CaptivePortal/index.volt
Labels: cleanup

#8849 Cron: Implement base_bootgrid_table and base_apply_button
  src/opnsense/mvc/app/controllers/OPNsense/Cron/Api/SettingsController.php
  src/opnsense/mvc/app/controllers/OPNsense/Cron/IndexController.php
  src/opnsense/mvc/app/controllers/OPNsense/Cron/forms/dialogEdit.xml
  src/opnsense/mvc/app/views/OPNsense/Cron/index.volt
Labels: cleanup

#8852 firewall/group: Implement base_bootgrid_table and base_apply_button
  src/opnsense/mvc/app/controllers/OPNsense/Firewall/Api/GroupController.php
  src/opnsense/mvc/app/controllers/OPNsense/Firewall/GroupController.php
  src/opnsense/mvc/app/controllers/OPNsense/Firewall/forms/groupEdit.xml
  src/opnsense/mvc/app/views/OPNsense/Firewall/group.volt
Labels: cleanup

#8855 firewall/category: Add HTML based standardized color input to form
  src/opnsense/mvc/app/controllers/OPNsense/Firewall/forms/categoryEdit.xml
  src/opnsense/mvc/app/views/OPNsense/Firewall/category.volt
  src/opnsense/mvc/app/views/layout_partials/form_input_tr.volt
  src/opnsense/www/js/opnsense.js
Labels: cleanup

#8862 firewall/automation: Fix issue with event binding
  src/opnsense/mvc/app/views/OPNsense/Firewall/filter_rule.volt
Labels: bug

#8863 vpn/ipsec: Pre-Shared Keys, Implement base_bootgrid_table and base_apply_button
  src/opnsense/mvc/app/controllers/OPNsense/IPsec/Api/PreSharedKeysController.php
  src/opnsense/mvc/app/controllers/OPNsense/IPsec/PreSharedKeysController.php
  src/opnsense/mvc/app/controllers/OPNsense/IPsec/forms/dialogPSK.xml
  src/opnsense/mvc/app/views/OPNsense/IPsec/pre_shared_keys.volt
Labels: cleanup

#8872 snapshots: Implement base_bootgrid_table
  src/opnsense/mvc/app/controllers/OPNsense/Core/SnapshotsController.php
  src/opnsense/mvc/app/controllers/OPNsense/Core/forms/snapshot.xml
  src/opnsense/mvc/app/views/OPNsense/Core/snapshot.volt
  src/opnsense/mvc/app/views/layout_partials/base_bootgrid_table.volt
Labels: cleanup

#8882 ids/policy: Implement base_bootgrid_table and base_apply_button
  src/opnsense/mvc/app/controllers/OPNsense/IDS/PolicyController.php
  src/opnsense/mvc/app/controllers/OPNsense/IDS/forms/dialogPolicy.xml
  src/opnsense/mvc/app/controllers/OPNsense/IDS/forms/dialogPolicyRule.xml
  src/opnsense/mvc/app/views/OPNsense/IDS/policy.volt
Labels: cleanup

#8883 monit: Remove dirty subsystem checks as base_apply_button does not track that
  src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/ServiceController.php
  src/opnsense/mvc/app/controllers/OPNsense/Monit/Api/SettingsController.php
  src/opnsense/mvc/app/models/OPNsense/Monit/Monit.php
Labels: cleanup

#8885 ui: Add checkmark to SimpleActionButton as additional indicator
  src/opnsense/www/js/opnsense_ui.js
Labels: feature

#8836 #8834/#8835: allow CSR to be downloaded from Sytem/Trust/Certificates
  src/opnsense/mvc/app/controllers/OPNsense/Trust/Api/CaController.php
  src/opnsense/mvc/app/controllers/OPNsense/Trust/Api/CertController.php
  src/opnsense/mvc/app/views/OPNsense/Trust/cert.volt
Labels: feature
