Repository opnsense/core, pull requests merged in 2025-05, with the labels that each got.

#8581 Add ability to specify pipe and queue masking using the *-ip6 specifiers.
  src/opnsense/mvc/app/models/OPNsense/TrafficShaper/TrafficShaper.xml
  src/opnsense/service/templates/OPNsense/Shaper/dnctl.conf
Labels: feature

#8645 dnsmasq: Allow static on IPv6 ranges
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
Labels: cleanup

#8648 dnsmasq: Add missing dhcp_boot to template
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPboot.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: cleanup

#8663 dnsmasq: Extract MAC from DUID in most cases to allow vendor information
  src/opnsense/scripts/dhcp/get_dnsmasq_leases.py
Labels: feature

#8667 dnsmasq: Add protocol selectpicker to leases view
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/Api/LeasesController.php
  src/opnsense/mvc/app/views/OPNsense/Dnsmasq/leases.volt
Labels: feature

#8678 dnsmasq: Allow lease_time 0 to set it infinite
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogHostOverride.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8679 dnsmasq: Add interface tag to dhcp boot options
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPboot.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/mvc/app/views/OPNsense/Dnsmasq/settings.volt
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8691 dnsmasq: Allow multiple tags per dhcp-boot, fix tag rendering by removing "-" like in other parts of template
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPboot.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: cleanup

#8699 dnsmasq: Create static host entries for all except partial IPv6 addresses
  src/etc/inc/plugins.inc.d/dnsmasq.inc
Labels: bug

#8702 dnsmasq: Fix physical interface in dhcp-boot
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: bug

#8706 Use CIDR notation for specifying masks to dnctl.
  src/opnsense/service/templates/OPNsense/Shaper/dnctl.conf
Labels: cleanup

#8709 dnsmasq: Add no-resolv option to prevent use of system defined dns servers
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/general.xml
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8710 dnsmasq: When dhcp-fqdn is active, set all dhcp domains as local
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8712 dnsmasq: Hide static mode in dhcp-range in advanced mode
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogDHCPrange.xml
Labels: cleanup

#8713 dnsmasq: Allow either empty IP or empty hostname for dhcp-host entries.
  src/etc/inc/plugins.inc.d/dnsmasq.inc
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.php
  src/opnsense/mvc/app/models/OPNsense/Dnsmasq/Dnsmasq.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: feature

#8743 dnsmasq: Set default to empty lease time for dhcp-host which results in auto calculated defaults
  src/opnsense/mvc/app/controllers/OPNsense/Dnsmasq/forms/dialogHostOverride.xml
  src/opnsense/service/templates/OPNsense/Dnsmasq/dnsmasq.conf
Labels: cleanup
